Update build_publish.yml

diff --git a/.github/workflows/build_publish.yml b/.github/workflows/build_publish.yml
--- a/.github/workflows/build_publish.yml
+++ b/.github/workflows/build_publish.yml
@@ -67,43 +67,43 @@ jobs:
           file: package/docker/Dockerfile
           push: true
           tags: |
-            bahmni/microfrontend-ipd:${{ env.ARTIFACT_VERSION }}
-            bahmni/microfrontend-ipd:latest
+            venevital/microfrontend-ipd:${{ env.ARTIFACT_VERSION }}
+            venevital/microfrontend-ipd:latest
 
-  push-translations:
-    name: Push Translations to Transifex
-    runs-on: ubuntu-latest
-    steps:
-      - name: 📥 Checkout code
-        uses: actions/checkout@v4
-      - name: Push Translations to Transifex
-        run: |
-          curl -o transifex.sh https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/transifex.sh
-          chmod +x transifex.sh
-          ./transifex.sh push
-          rm transifex.sh
-        env:
-          TX_TOKEN: ${{ secrets.TX_TOKEN }}
+  # push-translations:
+  #   name: Push Translations to Transifex
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: 📥 Checkout code
+  #       uses: actions/checkout@v4
+  #     - name: Push Translations to Transifex
+  #       run: |
+  #         curl -o transifex.sh https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/transifex.sh
+  #         chmod +x transifex.sh
+  #         ./transifex.sh push
+  #         rm transifex.sh
+  #       env:
+  #         TX_TOKEN: ${{ secrets.TX_TOKEN }}
 
-  trigger-workflow:
-    name: 🔁 Trigger workflow to deploy to Docker env
-    needs:
-      - trivy-scan
-      - build-publish-docker
-      - push-translations
-    runs-on: ubuntu-latest
-    env:
-      ORG_NAME: Bahmni
-      REPOSITORY_NAME: bahmni-docker
-      EVENT_TYPE: bahmni-ipd-microfrontend-event
-    steps:
-      - name: 🔧 Create repository_dispatch
-        run: |
-          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
-          if [ $trigger_result == 204 ]; then
-            echo "✅ Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
-          else
-            echo "❌ Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
-            cat trigger_response.txt
-            exit 1
-          fi
+  # trigger-workflow:
+  #   name: 🔁 Trigger workflow to deploy to Docker env
+  #   needs:
+  #     - trivy-scan
+  #     - build-publish-docker
+  #     - push-translations
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     ORG_NAME: Bahmni
+  #     REPOSITORY_NAME: bahmni-docker
+  #     EVENT_TYPE: bahmni-ipd-microfrontend-event
+  #   steps:
+  #     - name: 🔧 Create repository_dispatch
+  #       run: |
+  #         trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
+  #         if [ $trigger_result == 204 ]; then
+  #           echo "✅ Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
+  #         else
+  #           echo "❌ Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
+  #           cat trigger_response.txt
+  #           exit 1
+  #         fi
